### PR TITLE
fix some linter issues

### PR DESCRIPTION
**Pull request by s3rj1k**
Signed-off-by: s3rj1k <evasive.gyron@gmail.com>

### CODE REVIEW

**Comment by steambap** [comment]
What linter are you using? I already have 100% satisfaction from golint.

**Comment by s3rj1k** [comment]
golangci, revive

**Comment by steambap** [comment]
If you would fork this, how do you plan to fix generated code?

**Comment by s3rj1k** [comment]
Main issues are fixed in https://github.com/steambap/captcha/pull/4

**Comment by s3rj1k** [comment]
Is this PR safe to merge? If so, I'll rebase the one with globalvars

**Comment by steambap** [comment]
Sorry, no. I don't like to see weird comment all over my code. Also, global vars are bad, but there are exceptions, like the generated font data.

**Comment by s3rj1k** [comment]
This is exactly the behaviour that leads to forks and forks split open-source community efforts.

This should be a warning to future contributors.

**Pull request closed without merging**
