### PR TITLE
add base64 support

### PR DESCRIPTION
**Pull request by s3rj1k**
Signed-off-by: s3rj1k <evasive.gyron@gmail.com>

### CODE REVIEW

**Comment by steambap** [comment]
Sorry, I don't like this feature.
I think a better way to do this would be implement the `io.writer` interface that convert incoming bytes into base64 string. Another way to do it could be just return the `*image` data and let people do whatever with it.

**Comment by s3rj1k** [comment]
The main idea here that in newer browser you can directly use base64 encoded image like this:
```
<div>
    <p>Taken from wikpedia</p>
    <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
    9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
</div> 
```
This allows generating captcha image without any disk writes on busy server.

**Comment by s3rj1k** [comment]
"I think a better way to do this would be implement the io.writer interface that convert incoming bytes into base64 string." 

I am not sure how this will help with allocation and it will still copy from []bytes to string but definitely will complicate code.

**Comment by s3rj1k** [comment]
One can always do, so no need for exposing Image.image 
...
	var buff bytes.Buffer
	img.WriteImage(&buff)
	return base64.StdEncoding.EncodeToString(buff.Bytes())
...

**Comment by steambap** [comment]
Sorry for my bad explanation. I agree that base64 image is very useful.
However, I think `io.writer` is enough to let the user to do whatever they like with it. In your example, what if the user want URL-compatible base64 encoding? It would be best to leave the details to the user of the library.

**Comment by s3rj1k** [comment]
I was considering one case if for example some one would like to use external encoder, trubojpeg for example, exposing image.Image in this case will help.

As about base64, closing PR, my main interest is https://github.com/steambap/captcha/pull/4

**Pull request closed without merging**
